### ISSUE TITLE
Confusing List of Tutorials shown on OEP

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/tutorial#119]
Currently it seems like only tutorials from [this directory](https://github.com/OpenEnergyPlatform/tutorial/tree/develop/api) are linked on the OEP tutorials page. There are several issues with that. The naming often isn't ideal and the name is the only indicator for the content. There should be a descriptive name for all available tutorials.

- [x] Tutorials from the other directories should also be on the platform
- [ ] Tutorials that don't seem useful for anything should not be listed.
- [x] At any rate a descriptive name is helpful.

Originally an overview table was planned that also categorizes tutorials into video / text / jupyter. Is this still under development @johannwagner or has it dropped off the list of things that were worked on at some point? In future there should probably be a short description visible for every tutorial, visible before going there, too.

**Comment by jh-RLI** [comment]
I think this is already worked on in https://github.com/OpenEnergyPlatform/oeplatform/pull/630 . At least the tutorial naming. @TuPhanRLI If you have time atm could you try to run this branch on your machine? Then we can decide if this will solve part of the Issue or not.

**Comment by jh-RLI** [comment]
#### How the Tutorial name is set on the OEP:
The name of a tutorial displayed in the list on the OEP is taken from the 1st heading in the respective jupyter notebook.

**Comment by christian-rli** [comment]
This will be fixed with the new naming scheme that uses a json file to define the tutorials to be listed on the OEP. @jh-RLI introduced the new naming scheme in https://github.com/OpenEnergyPlatform/tutorial/pull/127 . If all goes well, only well named and relevant tutorials show up after the new release.
