### ISSUE TITLE
handling juyternotebook from develop 2 master

### ISSUE THREAD

**Issue by TuPhanRLI** [OpenEnergyPlatform/tutorial#122]
https://github.com/OpenEnergyPlatform/tutorial/blob/develop/upload/OEP_Research_Data_Publishing_Guidebook.ipynb
At the seciton "Introduction" the link "Upload Tutorial" is refering to a notebook in the "(https://github.com/OpenEnergyPlatform/tutorial/blob/feature/upload_process_tutorial/upload/OEP_Upload_Process_Data_and_Metadata.ipynb)" branch, which is already dead. Is it necessary to refer later on, to the develobranch after merging into the masterbranch?

**Comment by jh-RLI** [comment]
Did u fix the link? I renamed the [jupyter notebook](https://github.com/OpenEnergyPlatform/tutorial/tree/develop/upload) this week. There is one upload tutorial using oem2orm and one using the oep-client. I do not know what you mean by referring to develop branch after merge.

**Comment by TuPhanRLI** [comment]
I couldn't fix the link because I didn't know how to handle the referred "Upload Tutorial". Also if I refer to one of the 2 (oem2orm and oepclient) its still linked to the develop branch. Just wanted to know how deal with it after te merge into masterbranch

**Comment by jh-RLI** [comment]
fixed in 40e99a1009b9b3bf60cc15ca2c6b6b02d6211b26
