### ISSUE TITLE
Handling Metadata String from viewpoint of the user

### ISSUE THREAD

**Issue by TuPhanRLI** [OpenEnergyPlatform/tutorial#124]
At the following DatarewieProzess, it wasnt really clear to the user to attache the metadata at the issue. Otherwise there is gonna be a workaround for cloning and pushing back to github and finally initialize a pull request. 

https://github.com/OpenEnergyPlatform/data-preprocessing/issues/new?assignees=christian-rli%2C+jh-RLI%2C+Ludee&labels=review&template=metadata-and-data-review.md&title=Review%3A+NameOfDataset

**Comment by christian-rli** [comment]
I added a note that attaching metadata into a comment in the issue is also an option.
