### ISSUE TITLE
Grouping of tutorials

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/tutorial#135]
Expand the json strings that contain the tutorial metainformation. Include the following keys (possible values in brackets):

- language (de, en, fr)
- creator (freetext) potentially copyright might be a better key name
- license (CC0, AGPL)
- contact (E-mail, github-handle, o.ä)
- level (beginner, intermediate, expert)
- medium (video, text, jupyter notebook)

This approach will work for the jupyter notebook tutorials.
@jh-RLI please find out how level information is stored in the OEDB at the moment and comment in this issue. 
If you can, expand with the terms above in the OEDB, so we have matching sets of metainformation.

@Ludee There already is an issue for implementing the table-like design, which includes a classification for tutorials. @johannwagner you are assigned to this (https://github.com/OpenEnergyPlatform/oeplatform/issues/462 ). Is there any plan for implementation?

**Comment by jh-RLI** [comment]
I can add the fields to the text/markdown tutorials on OEP. There the level info is stored with the tutorial content in a table (model) and can be extended. I will start implementing the functional Django stuff and update the GitHub tutorial meta.json with the info above. Maybe @johannwagner can implement the UI design afterwards? I could do this, but it would look very basic and not like the mockup.

**Comment by johannwagner** [comment]
I can handle the UI design. Hit me up @ Telegram, if you finish your part.

**Comment by jh-RLI** [comment]
@christian-rli we still miss the category. We just have 'I/O' and 'Introduction' ATM (see in OEP-markdown tutorials). These categories could be used to group the tutorials when a User visits the tutorial area. This would extend the current mockup I believe.

**Comment by jh-RLI** [comment]
The categories are derived from names defined in https://github.com/OpenEnergyPlatform/oeplatform/issues/394

**Comment by jh-RLI** [comment]
I created a meta.json template/example:
https://github.com/OpenEnergyPlatform/tutorial/blob/e78698645ae1b563589f78e4dcffd6288ea32092/template/tutorial_metadata.json#L1-L10

I will start updating all the meta.json for each tutorial.

**Comment by Ludee** [comment]
PLease rename "github" to "github_contact"

**Comment by christian-rli** [comment]
From our discussion: categories should be:     "category": "General; Publication; Upload/Download; Data Structure; Ontology; Other",

**Comment by jh-RLI** [comment]
Included the review result :+1: 
See updated [comment ](https://github.com/OpenEnergyPlatform/tutorial/issues/135#issuecomment-796913231)  above ^

**Comment by jh-RLI** [comment]
We updated the meta.json and added database identifiers and readable names: 
https://github.com/OpenEnergyPlatform/tutorial/blob/53d9b2e35e671dd994b9e01717ad29130f82afe3/template/tutorial_metadata_template.json#L1-L23

**Comment by christian-rli** [comment]
@johannwagner this is the other issue i meant to link in our developer meeting yesterday. As I see it, it is basically done and is just waiting for implementation on the website. If you have any questions talk to @jh-RLI

**Comment by johannwagner** [comment]
@jh-RLI mentioned a mock-up, that I do not know yet. Is it uploaded somewhere?
