### ISSUE TITLE
Update checklist for open data tutorial

### ISSUE THREAD

**Issue by stap-m** [OpenEnergyPlatform/tutorial#136]
The tutorial https://openenergy-platform.org/tutorials/1/ needs an update:
- I don't understand the first sentence. Can it be deleted?
- no.3 "detailed" instead of "de-tailed"
- no.4 the link leads to a GitHub tutorial. It should redirect to the licencing tutorial on the OEP, probably this one: https://openenergy-platform.org/tutorials/jupyter/tutorial_open-data-licenses/
- Last sentence: Begin with Capital letter, end with ".", inbetween "can" instead of "con"   

This is important for the PtJ link list!

**Comment by christian-rli** [comment]
I extended the description for no 1, because I misread your first bullet point. Then I deleted the malformed redundant sentence. I also included all of the other suggested changes.
