### ISSUE TITLE
Update tutorial on database conform data

### ISSUE THREAD

**Issue by stap-m** [OpenEnergyPlatform/tutorial#137]
The tutorial https://openenergy-platform.org/tutorials/7/ needs an update:

- add new lines for a), b) etc... for a clear structure throughout the turorial
- Headlines with Capital letters "Good example", "Bad example"
- Section Good example: suggestion to change enumeration to "Option 1", "Option 2" (right now it is 1. and 1.)
- no.2 ...see figure **"Poor example"** and **"Good example"** on ..., Same for no. 6 an no. 12
- no.7 and no.8 anwer what is compulsory/ OEP convention
- no.9 the italic part is 
- no.10c: "In case of time intervals, do you have a left stamp, right stamp or middle stamp": we should use OEO terms for that e.g.: "In case of time intervals, which time stamp alignment do you use, start, middle or end alignment? (see OEO time stamp alignment)" @MGlauer can we link to a specific class? The IRI http://openenergy-platform.org/ontology/oeo/OEO_00140044 just leads to http://openenergy-platform.org/ontology/oeo
- no.11: e.g. "Make sure your model (input and) output data has always the same format..." instead of "Implement your model that the result has always the same format..."
 
This is important for the PtJ link list!

**Comment by christian-rli** [comment]
I implemented all comments and linked to the IRI, even though it only directs to the OEO. I believe the IRI is meant to lead to some subclass specific page at some point @MGlauer ? Closing this issue, though.
