### ISSUE TITLE
Update tutorial on how to upload data

### ISSUE THREAD

**Issue by stap-m** [OpenEnergyPlatform/tutorial#138]
The tutorial https://openenergy-platform.org/tutorials/8/ needs an update:

- First sentence; "... two different **paths** may be selected."
- Start both section headlines with  "The users who ..." and unify singular / plural
- Section 1: "... The sandbox is not visible**. The** upload process is very fast but beware, the sandbox gets deleted regularly. Once accustomed to the sandbox the user may use the model draft and **upload real project data**" (delete _its_ !)
- Section 2: "... which is very intuitive and **provides good support** for all mandatory fields."" 
- Final sentence: "As soon as the data is *finalized* and the user makes no further changes, the data can be permanently stored at the corresponding topic. **There, the stored data becomes visible to others. The ** upload process takes some time and ..."" Question: topic or schema? Question: "and the data is stored in GitHub." really??

This is important for the PtJ link list!

**Comment by christian-rli** [comment]
I implemented the changes. Stored on GitHub are the metadata and their evolution - I changed the description accordingly.
