### ISSUE TITLE
typo in heading needs fixing

### ISSUE THREAD

**Issue by robbiemorrison** [OpenEnergyPlatform/tutorial#144]
"Tutorial: Open Data Licensensing Guide" heading has a bad typo → "Licensing"

https://openenergy-platform.org/tutorials/jupyter/tutorial_open-data-licenses/

**Comment by stap-m** [comment]
Please fix this soon, thanks.

**Comment by jh-RLI** [comment]
This is already fixed by @christian-rli 
see: https://github.com/OpenEnergyPlatform/tutorial/commit/54bc5076c64de649ac07f5aaa9cebd2ae6310935
