### ISSUE TITLE
Lack of metadata guidelines and standards

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/tutorial#15]
As a   user, I would like to use the metadata guidelines and common standards for my   and other metadata so that I am compatible    to other standards.

**Comment by christian-rli** [comment]
RequirementSpecificationID=26

**Comment by christian-rli** [comment]
The metadata standard has its own repository and has a [full key description with examples](https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/metadata/v140/metadata_key_description.md). There is a [review issue template](https://github.com/OpenEnergyPlatform/data-preprocessing/issues/new/choose) for the review of newly created metadata as well as a [manual](https://github.com/OpenEnergyPlatform/data-preprocessing/blob/master/data-review/manual/review_manual.md) on how to review metadata. A process for Improvements to any of these has been implemented as well with another [issue template](https://github.com/OpenEnergyPlatform/data-preprocessing/issues/new/choose) which is referenced at the appropriate locations.
