### ISSUE TITLE
Create a MWE with geopackage export

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/tutorial#2]
- [ ] Create a Jupyter Notebook to access a table
- [ ] Plot geographic data on a map
- [ ] export data to local geopackage

**Comment by christian-rli** [comment]
Use the template tutorial for this https://github.com/OpenEnergyPlatform/tutorial/tree/develop/template
Also, don't support shapefiles. Explain the export to geojson and geopackage

**Comment by TuPhanRLI** [comment]
The tutorial OEP_API_tutorial_part3 with the title: "Tutorial 3 - How to work with the OpenEnergy Platform (OEP)"
is already covering most of the requested requirements. The only exception is the export to a local geopackage. 
Therefore the question is if we should keep the tutorial or create a separate one. Furthermore, we should rethink the labeling of the tutorial part 1 to 4.
