### ISSUE TITLE
tutorial for csv upload wizard

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/tutorial#21]
As a   user I would like to see a tutorial for the csv Upload Wizard (usage, allowed   formats...) so that I can use the wizard correctly.

**Comment by christian-rli** [comment]
Other required tutorials are listed in this issue: https://github.com/OpenEnergyPlatform/examples/issues/8

RequirementSpecificationID=53

**Comment by han-f** [comment]
To be tackled once wizard is available. 
Wizard discussed in #346

**Comment by christian-rli** [comment]
Use the [template tutorial](https://github.com/OpenEnergyPlatform/tutorial/tree/develop/template) for this. A good place for the tutorial is the directory [upload](https://github.com/OpenEnergyPlatform/tutorial/tree/develop/upload).

**Comment by wingechr** [comment]
Done: https://openenergy-platform.org/tutorials/15
