### ISSUE TITLE
Implement OEP metadata version v1.4

### ISSUE THREAD

**Issue by Ludee** [OpenEnergyPlatform/tutorial#23]
After collecting a lot of feedback, the  OEP metadata version v1.4 is ready to be used.
Minor changes can still be made, so ensure to pull the [template](https://github.com/OpenEnergyPlatform/examples/blob/master/metadata/oep_metadata_template.json) and example regularly. 

New features:
* 100% data package conform
* better CSV implementation
* link to context (document, project, grant no.)

**Comment by han-f** [comment]
Thanks for completing this! That means we can use this in our uploading scripts once this structure has been implemented on the oep, correct? Otherwise we send information that cannot be shown anywhere ...

**Comment by klarareder** [comment]
Can this issue be closed now? As far as I know ist 1.4 already released.
