### ISSUE TITLE
[metadata] Create conversion tool from v1.3 to v1.4 

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/tutorial#34]
Create a tool that translates JSON-strings from metadata version 1.3 to version 1.4. KilianZimmerer already created one from versions 1.2 to 1.3. 
Keep information from old strings and create placeholder structure for new necessary values.

**Comment by Bachibouzouk** [comment]
This will be done by @4lm in https://github.com/OpenEnergyPlatform/omi

**Comment by christian-rli** [comment]
omi supports this functionaity now. therefore closing this issue.
