### ISSUE TITLE
Include in Tutorials first steps

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/tutorial#42]
The Tutorials start with an Installed Anaconda version. It would be good to include the first steps for first time users: setup of virtual environment etc.
If possible it would be nice if the tutorials could be grouped into: first time user, some python experience, expert and hence start at the respective points.

**Comment by christian-rli** [comment]
I included video tutorials (from youtube) for jupyter notebooks and setup in windows and linux ( https://openenergy-platform.org/tutorials/9/ and https://openenergy-platform.org/tutorials/10/ ). Categorisation for tutorials is implemented. The category is store in the database. Unfortunately it's not visible in the overview yet. This still depends on https://github.com/OpenEnergyPlatform/oeplatform/issues/462 

I will progressively link to these tutorials in all jupyter notebooks.
