### ISSUE TITLE
how to use Jupyter Notebook Tutorial

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/tutorial#45]
For people who have never worked with jupyter

**Comment by christian-rli** [comment]
Use the [template tutorial](https://github.com/OpenEnergyPlatform/tutorial/tree/develop/template) for this. A good place for the tutorial is the directory [other](https://github.com/OpenEnergyPlatform/tutorial/tree/develop/other).

**Comment by christian-rli** [comment]
We should reference existing, external sources for this. There is a good [7 minute video](https://www.youtube.com/watch?v=jZ952vChhuI ) that walks windows users through jupyter and another [linux video](https://www.youtube.com/watch?v=eY4JFm74oi4) that includes installation instructions.

Creating our own video for this would not significantly add value. So once the tutorials page is live, just linking them will solve the issue.

**Comment by christian-rli** [comment]
Videos are uploaded to the OEP tutorial section: [intro video](https://openenergy-platform.org/tutorials/9/) and [linux video](https://openenergy-platform.org/tutorials/10/)
