### ISSUE TITLE
Tutorial: OEP usage

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/tutorial#46]
An overview of how to work with the OEP Web - Where to find what...

**Comment by klarareder** [comment]
I made a first draft with 10 Points:
Top 10 Best practices working with the OEP:
1.	Check you know the purpose and functionality of the OEP - watch Tutorial advertisingOEP #46, #50
2.	Check to be familiar with licenses - watch tutorial OpenEnergyPlatform/oeplatform#158 - click this link to more information XX
3.	Check all input data has a free license and can be published
4.	Make sure data is database conform - watch tutorial #48
5.	Make yourself familiar with the up and download - watch tutorial OpenEnergyPlatform/oeplatform#302, #1
6.	Make sure metadata is filled
7.	Make sure factsheets are filled
8.	Make sure in your report/poster etc. to place an open license
9.	Review data of others - see Guidance of Review (click link XX)
10.	Promote the OEP to your colleagues and friends

**Comment by han-f** [comment]
A guidance that includes a "one-stop-shop" for a first contribution of data and metadata to the OEP using the REST-API is under development. It also includes a how-to register on the OEP and github.
See also [here](https://github.com/OenEnergyPlatform/oeplatform/issues/405)

**Comment by han-f** [comment]
Status, see @wingechr remark in https://github.com/OpenEnergyPlatform/oeplatform/issues/405: 
> Chapter 1 and 2 of the document are still valid, but chapter 3 (factsheets) needs rework after the chanegs on the platform has been implemented. Currently, his is a little broken.

**Comment by wingechr** [comment]
@han-f @klarareder: I thinkthis can be closed with the tutorial version of the guidance document?

**Comment by klarareder** [comment]
I agree
