### ISSUE TITLE
Tutorial: what is an Ontology and how does it work?

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/tutorial#49]

**Comment by christian-rli** [comment]
Use the [template tutorial](https://github.com/OpenEnergyPlatform/tutorial/tree/develop/template) for this. A good place for the tutorial is the directory [other](https://github.com/OpenEnergyPlatform/tutorial/tree/develop/other).

**Comment by christian-rli** [comment]
Link to the lightning talk on the OEO from 13 May 2020: https://openmod-initiative.org/temp-file-transfer-robbie/2020-openmod-mw03-02-hofmann-open-energy-ontology-84af60ae.mp4

**Comment by christian-rli** [comment]
The OEP tutorial section now includes the [ontology video](https://openenergy-platform.org/tutorials/5/).
