### ISSUE TITLE
Tutorial: How to document

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/tutorial#51]
How to work with Issues, and document the code

**Comment by christian-rli** [comment]
Is this really done best in a tutorial or should it be a good self-description in the repository with template issues and so on?

**Comment by christian-rli** [comment]
Working with issues and documenting code are both vast topics. Working with issues, put most simply, follows the github workflow. How to document code depends very much on the repository and what was edited. This issue isn't formulated clearly. Therefore closing it.
