### ISSUE TITLE
Metadata documentation suggestion

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/tutorial#56]
The current metadata documentation holds examples for the specific entries which is useful. It would be helpful to also have a list of allowed column data types.  This applies to the case for working with the API.

**Comment by han-f** [comment]
Now I found it here: https://github.com/OpenEnergyPlatform/examples/wiki/Metadata-Description 
It would be helpful to link to this at a prominent place on the OEP.  Linked to ticket 
https://github.com/OpenEnergyPlatform/oeplatform/issues/411

**Comment by Bachibouzouk** [comment]
The metadata documentation will be moved to https://github.com/OpenEnergyPlatform/metadata

**Comment by MGlauer** [comment]
Shouldn't we move this issue then?

**Comment by Bachibouzouk** [comment]
> Shouldn't we move this issue then?

@MGlauer - This is my plan (for all metadata issues), but I wanted to wait enough time so that @han-f (or other users) can know that the issues with metadata will be moved :)

**Comment by christian-rli** [comment]
The documentation has moved to the metadata repository and the allowed data types are available in a json schema [here](https://github.com/OpenEnergyPlatform/metadata/blob/develop/metadata/v140/schema.json) - thank you for the good work @4lm . 

A link to the description at a prominent location will be implemented with the redesign, but as you mentioned, this is called for in another issue. Can this issue be closed @han-f ?
