### ISSUE TITLE
UML diagrams on OEP?

### ISSUE THREAD

**Issue by han-f** [OpenEnergyPlatform/tutorial#60]
We are looking into creating an UML diagram based on the tutorial 
https://github.com/OpenEnergyPlatform/examples/blob/master/omg/UML%20Tutorial.ipynb 
and wonder where on the OEP the UML diagrams would be displayed best in the future? Were there already thoughts on this?

**Comment by stap-m** [comment]
@MGlauer,  @Ludee and I spoke about it in the jour-fixe meeting today. We agreed that the bundles are the right place for UML diagrams. Ludee and @bmlancien are going to propose a more detailed solution.
