### ISSUE TITLE
Make Jupyter Notebook Tutorials more understandable for programming Newcomers

### ISSUE THREAD

**Issue by pkassing** [OpenEnergyPlatform/tutorial#63]
I worked through all the Jupyter Notebook tutorials and took notes on points that I, as a newcomer to programming found hard to understand: 
These are the points that I already worked into Part 1 of the Jupyer Notebook @Ludee, please have a look at it. My explanations might interfere with a fluid working through the notebook. 
these are the points that I explained
in part 1: 
-	Explanation that the request package is handling http protocol communication 
-	Where are the tables stored? – link to “schemas” and “tables”
-	Missing explanation of the data structure of tables 
-	Which operations do I need an authorization token for?
-	Explanation that authorization token has to be included as a header in the request 
-	“insert data”, if you want to insert multiple lines of data, like the two power plants in this case, each row is a dictionary in a list? 

I pushed the altered version to github.

I found that the following points still have to be explained: 
in part 1: 
-	"Query table columns" -is the returned json the specification of the column header “capacity”? this should be explained shortly 
-	 “insert data into a specific row” – does this replace the original row, or is the originals row shifted one step downwards?
-	Alter data in table?  What does /rows/{id}'.format(id=row), stand for ? 

in part 2: 
-	Filter: if something is searched for, the url has to include a “?” after rows/ ? This should be mentioned 
-	“limit” – missing explanation: the limit filter limits the number of results that you get if you search for rows or columns. In this case, as the filter is equal to two, only to rows are returned
-	“more options” – more detailed explanation / some examples of usage of “where”- filter ? 

in part 3: 
- a bit more explanation of what is done in this part would be great, - what does vg stand for? 
Which relation do the data included in “boundaries” and “supply” have ?
-	Short explanation of the modules ? 

Btw, the "order by" filter is working now

**Comment by jh-RLI** [comment]
Working on solving this issue in #69 and  #73.

**Comment by jh-RLI** [comment]
This ticket can be closed if the team agrees to the revised version.

**Comment by christian-rli** [comment]
I agree with the revised versions. @klarareder this repository is being restructured with new directories for upload and download. Additionally, a subpage for tutorials that is supposed to pick up first time users is under development on the oep. The ticket can be closed. 

@jh-RLI : There should be a merge of develop into master however, which I'm going to carry out today. This hasn't been done in a while, so I hope I'm not running into any conflicts. In any case, let's try to stick to the driessen workflow afterwards.
