### ISSUE TITLE
Shut down examples repository and create a new one, named tutorials

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/tutorial#80]
In a small group we discussed another restructuring of oef repositories. In short, the suggestion I'm making here is to shut down this repository and open a tutorial repository as partial replacement. The reasons are as follows.

Shortcomings of this repository:
- It isn't very well structured. It contains folders for the api, data, metadata and omg (the last of which is not explained anywhere. (None of them really are, but this one really gives no context))
- These folders contain tutorials and examples with no particular systematic order. Examples should be located in the context of the software/code that they exemplify, or as part of an automatic test. Tutorials aren't examples.
- It's partly redundant. E.g. metadata moved to its own repository and now some remnants remain here, only waiting for deletion.

Improvements a new or restructured repository would bring:
- examples would always be created in the context of the actual software/code, or in cases where that already is the case, it would no longer be redundant
- A new repository would have a clear focus on tutorials and could therefore be better structured. It wouldn't have to mix reference implementations and descriptive manuals.
- There should be (sub)folders for all other repositories of the oef.
- As I'm thinking about structuring documentation of all kinds in general and how to separate them, this makes sense. Examples belong to the code. Technical documentation lives in readthedocs. Tutorials need their own space.
- The oep has one location it draws its standard tutorials from. It's clear to the non-involved where tutorials live and where to make suggestions for improvements

Why not restructure this instead of opening a new one?
- After clearing the redundancies of this repository mostly tutorials or rudiments thereof would remain
- One way to restructure would be to just rename this repository to tutorials. This would have similar downsides to creating a new one (mainly broken links)
- Deleting the old one enforces an orderly move of all issues, code snippets and comments to a more fitting permanent location and doesn't allow to "just keep this here for now"

Necessary tasks that would need to be done:
- Fix links (again) to all tutorials
- move issues
- move examples
- create, structure and fill new repository
- Turn list of needed tutorials from nextcloud into issues of new repository (this will need to be done in any case)

I would carry out all or at least most of these tasks, but since this is quite a significant change, I would like to discuss it here before going on with it. So please feel free to comment below reasons against this move or make alternative suggestions @han-f @jh-RLI @klarareder @l-emele @Ludee  @MGlauer @stap-m @wingechr . 

We can further discuss this in our next call.

**Comment by Ludee** [comment]
IMO: Keep the repo and start restructuring the existing stuff.

**Comment by christian-rli** [comment]
It was decided to rename the repository instead, which is much less of a hassle. A new folder structure has been started. Other points of this issue either belong to other repositories or can be implemented step by step in smaller issues. Therefore closing this issue.
