### ISSUE TITLE
Missing list of recommended licenses

### ISSUE THREAD

**Issue by christian-rli** [OpenEnergyPlatform/tutorial#87]
The OEP only allows open data to be uploaded. It is not however clearly defined or described what we mean by that precisely. @Ludee please provide a list of compatible licenses and a recommendation. This information then needs to be added to all tutorials that have explain upload functions.

**Comment by Ludee** [comment]
Create a PR and push the "Open Data Licenses Guide" to master branch and make available at the OEP.

**Comment by christian-rli** [comment]
This in online under tutorials since the latest release.
