### ISSUE TITLE
Upload best practice checklist working with open data to tutorials page

### ISSUE THREAD

**Issue by klarareder** [OpenEnergyPlatform/tutorial#9]
As a   sponsor/user I would like to see a guide on how to work with open data (best   practice, checklist 10 points).

**Comment by Ludee** [comment]
Consider: [Open Data for Electricity Modeling ](https://www.bmwi.de/Redaktion/EN/Publikationen/Studien/open-Data-for-electricity-modeling.html)

**Comment by christian-rli** [comment]
RequirementSpecificationID=61

**Comment by klarareder** [comment]
I made a first draft with 10 Points:

Top 10 Best practices working with the OEP:
1.	Check you know the purpose and functionality of the OEP - watch Tutorial advertisingOEP #46, #50
2.	Check to be familiar with licenses - watch tutorial OpenEnergyPlatform/oeplatform#158 - click this link to more information XX
3.	Check all input data has a free license and can be published
4.	Make sure data is database conform - watch tutorial #48
5.	Make yourself familiar with the up and download - watch tutorial OpenEnergyPlatform/oeplatform#302, #1
6.	Make sure metadata is filled
7.	Make sure factsheets are filled
8.	Make sure in your report/poster etc. to place an open license
9.	Review data of others - see Guidance of Review (click link XX)
10.	Promote the OEP to your colleagues and friends

**Comment by klarareder** [comment]
The list above is rather a tutorial/workflow on how to work with the OEP. Is that what we understood with this issue or was it rather: 

"A checklist what to do before getting started in an open data project?"

I think it is acually pretty much the same, but might have to be rewritten a litte or coloured: Points 1-5 before getting started with a project, 6-10 during a project and before finishing it.

**Comment by christian-rli** [comment]
I think the phrasing of this issue was slightly changed at some point without me noticing. I believe originally the goal here was to provide a manual to a funding agency on criteria of what makes a project 'open'. The idea was to offer a tool for detecting open-washing. The checklist (as i understood it) meant to provide things like a selection of appropriate open licenses, a list of what data needs to be accessible at what point in time and so on.
The checklist can in turn then be used for the creation of an open data project, so I guess the answer to your question is: in this issue we rather meant 'a list of what defines an open data project' as opposed to 'how to work with the OEP'.

**Comment by klarareder** [comment]
Ok, than I move this checklist to the Turorial Issue.

**Comment by klarareder** [comment]
In 'Open Data for Electricity Modeling ' on page 39 is already a checklist which is what I understand from the purpose of this issue.

**Comment by klarareder** [comment]
I merged the two checklists from Open Data for Electricity Modeling into one:

funding agency:

When requiring open data when funding research. All data generated in publicly funded research projects should be available to the public and the modeling community for reuse. This means the following 6 points should be fulfilled:

1.	All data should be available in machine-readable formats.
2.	 All data is accompanied with metadata.
3.	Provide detailed and up-to-date documentation. The documentation should include de-tailed information about measurement and estimation techniques.
4.	The final data should be published under an open license. To facilitate analysis and reuse, data should be published under an established open license. We recommend a public domain dedication; where this is not possible, an attribution license is the second best choice, such as Creative Commons Attribution 4.0.
5.	The data should be published through centralized platforms, which permit download of data in bulk, be version controlled, and be permanently available, preferably through a Digital Object Identifier and provide API web access.
6.	All uploaded data from third parties should indicate who holds intellectual property rights. It must be transparent to users as to who holds the intellectual property rights.

more detailed information on these topics con be found in 'Open Data for Electricity Modeling'

**Comment by Bachibouzouk** [comment]
@klarareder , @christian-rli - it seems to me that there is a list now and thus the issue can be closed. The question is where is it stored?

Meta-comment for github workflow :
1. Create an issue describing the problem and providing short idea (brainstorming style) on how to tackle the issue.
2. Create a new branch to solve the problem. If more than one idea is worth trying, then create different branches
3. Create a [Pull Request Draft](https://github.blog/2019-02-14-introducing-draft-pull-requests/) and write at least "Closes #<number of the related issue>" in the description. The Draft should point to develop or master.
4. Push your daily commits on this/these Pull Request Drafts
5. Once a solution seems to work, [switch the draft to a Pull Request](https://help.github.com/en/articles/changing-the-stage-of-a-pull-request) and choose a reviewer
6. Merge in develop/master

For example, the list could be contained in a file and each version of the list would be stored in different commits :)

**Comment by stap-m** [comment]
Do we find a place on the newly designed OEP to publish this list? 
Its not a really a tutorial, though...

**Comment by christian-rli** [comment]
@bmlancien and I have talked about the layout and structure of the tutorials page. There is going to be a collection of simple text pages, videos and jupyter notebooks. While the list might not be a tutorial in and of itself, it contains relevant information that can function as a guide on what kind of data can be found on and uploaded to the platform and there should be space for this as a simple text page among the tutorials. We should upload it as soon as the structure exists. I'm renaming this ticket accordingly.
@bmlancien could you upload your progress with the redesign/restructuring of the website in [this ticket](https://github.com/OpenEnergyPlatform/oeplatform/issues/370)? Thank you :)

**Comment by christian-rli** [comment]
Use the [template tutorial](https://github.com/OpenEnergyPlatform/tutorial/tree/develop/template) for this.

**Comment by christian-rli** [comment]
@Ludee just recently wrote a document on [open licenses that come recommended for use in the OEP](https://github.com/OpenEnergyPlatform/tutorial/blob/develop/other/tutorial_open-data-licenses.ipynb). I think it can be referenced in the list @klarareder :)

**Comment by klarareder** [comment]
@klarareder  Include this reference in the final document:
https://github.com/OpenEnergyPlatform/tutorial/blob/develop/other/tutorial_open-data-licenses.ipynb

**Comment by Ludee** [comment]
ToDO: Create PR, publish and link on OEP.

**Comment by klarareder** [comment]
I added the link and published the tutorial
